application: templatesbench
version: 1
runtime: python
api_version: 1

handlers:
- url: /bottlesimpletemplate/.*
  script: /app/bottle/bottleTest.py
  
- url: /bottledjango/.*
  script: /app/bottleDjango/bottleTestDjango.py
  
- url: /bottlemako/.*
  script: /app/bottleMako/bottleTestMako.py
  
- url: /bottlejinja/.*
  script: /app/bottleJinja/bottleTestJinja.py
  
- url: /bottletenjin/.*
  script: /app/bottleTenjin/bottleTenjinTest.py
  
- url: /bottletenjcache/.*
  script: /app/bottleTenjinCache/bottleTenjinCacheTest.py
  
- url: /bottlebreve/.*
  script: /app/bottleBreve/bottleBreveTest.py
  
- url: /bottletemplator/.*
  script: /app/bottleTemplator/bottleTestTemplator.py
  
- url: /webpytemplator/.*
  script: /app/webpy/webpyTest.py
  
- url: /webpydjango/.*
  script: /app/webpyDjango/webpyTestDjango.py
  
- url: /webpyjinja/.*
  script: /app/webpyjinja/webpyJinjaTest.py
  
- url: /webpymako/.*
  script: /app/webpymako/webpyMakoTest.py
  
- url: /webpybreve/.*
  script: /app/webpybreve/webpyBreveTest.py
  
- url: /webpysimpletemplate/.*
  script: /app/webpySimpleTemplate/webpyTestSimpleTemplate.py
  
- url: /webpytenjin/.*
  script: /app/webpytenjin/webpyTenjinTest.py
  
- url: /webpytenjcache/.*
  script: /app/webpytenjinCache/webpyTenjinCacheTest.py
  
- url: /webappdjango/.*
  script: /app/gnative/gnative.py
  
- url: /webappmako/.*
  script: /app/gmako/gmako.py
  
- url: /webappjinja/.*
  script: /app/gjinja/gjinja.py
  
- url: /webappsimpletemplate/.*
  script: /app/gSimpleTemplate/gTestSimpleTemplate.py
  
- url: /webapptenjin/.*
  script: /app/gtenjin/gTenjinTest.py
  
- url: /webapptenjcache/.*
  script: /app/gtenjinCache/gTenjinCacheTest.py
  
- url: /webapptemplator/.*
  script: /app/gtemplator/gTestTemplator.py
  
- url: /webappbreve/.*
  script: /app/gbreve/gBreveTest.py
  
- url: /flaskjinja/.*
  script: /app/flask/flaskTest.py
  
- url: /flaskdjango/.*
  script: /app/flaskDjango/flaskTestDjango.py
  
- url: /flaskmako/.*
  script: /app/flaskmako/flaskTestMako.py
  
- url: /flasksimpletemplate/.*
  script: /app/flaskSimpleTemplate/flaskTestSimpleTemplate.py
  
- url: /flasktenjin/.*
  script: /app/flaskTenjin/flaskTenjinTest.py
  
- url: /flasktenjcache/.*
  script: /app/flaskTenjinCache/flaskTenjinCacheTest.py
  
- url: /flasktemplator/.*
  script: /app/flaskTemplator/flaskTestTemplator.py
  
- url: /flaskbreve/.*
  script: /app/flaskBreve/flaskBreveTest.py
  
- url: /tipfyjinja/.*
  script: /app/tipfy/tipfyTest.py
  
- url: /tipfydjango/.*
  script: /app/tipfyDjango/tipfyTestDjango.py
  
- url: /tipfymako/.*
  script: /app/tipfymako/tipfyTestMako.py
  
- url: /tipfysimpletemplate/.*
  script: /app/tipfySimpleTemplate/tipfyTestSimpleTemplate.py
  
- url: /tipfytenjin/.*
  script: /app/tipfyTenjin/tipfyTenjinTest.py
  
- url: /tipfytenjcache/.*
  script: /app/tipfyTenjinCache/tipfyTenjinCacheTest.py
  
- url: /tipfytemplator/.*
  script: /app/tipfyTemplator/tipfyTestTemplator.py
  
- url: /tipfybreve/.*
  script: /app/tipfyBreve/tipfyBreveTest.py
  
- url: /webobbreve/.*
  script: /app/webobBreve/webobTestBreve.py
  
- url: /webobdjango/.*
  script: /app/webobDjango/webobTestDjango.py
  
- url: /webobjinja/.*
  script: /app/webobJinja/webobTestJinja.py
  
- url: /webobmako/.*
  script: /app/webobMako/webobTestMako.py
  
- url: /webobsimpletemplate/.*
  script: /app/webobSimpleTemplate/webobTestSimpleTemplate.py
  
- url: /webobtemplator/.*
  script: /app/webobTemplator/webobTestTemplator.py
  
- url: /webobtenjin/.*
  script: /app/webobTenjin/webobTestTenjin.py
  
- url: /webobtenjcache/.*
  script: /app/webobTenjinCache/webobTestTenjinCache.py
  
- url: /wsgibreve/.*
  script: /app/wsgiBreve/wsgiTestBreve.py
  
- url: /wsgidjango/.*
  script: /app/wsgiDjango/wsgiTestDjango.py
  
- url: /wsgijinja/.*
  script: /app/wsgiJinja/wsgiTestJinja.py
  
- url: /wsgimako/.*
  script: /app/wsgiMako/wsgiTestMako.py
  
- url: /wsgisimpletemplate/.*
  script: /app/wsgiSimpleTemplate/wsgiTestSimpleTemplate.py
  
- url: /wsgitemplator/.*
  script: /app/wsgiTemplator/wsgiTestTemplator.py
  
- url: /wsgitenjin/.*
  script: /app/wsgiTenjin/wsgiTestTenjin.py
  
- url: /wsgitenjcache/.*
  script: /app/wsgiTenjinCache/wsgiTestTenjinCache.py
  
- url: /web2django/.*
  script: /app/g2native/g2native.py

- url: /web2mako/.*
  script: /app/g2mako/g2mako.py

- url: /web2jinja/.*
  script: /app/g2jinja/g2jinja.py

- url: /web2simpletemplate/.*
  script: /app/g2SimpleTemplate/g2TestSimpleTemplate.py

- url: /web2tenjin/.*
  script: /app/g2tenjin/g2TenjinTest.py
  
- url: /web2tenjcache/.*
  script: /app/g2tenjinCache/g2TenjinCacheTest.py

- url: /web2templator/.*
  script: /app/g2templator/g2TestTemplator.py

- url: /web2breve/.*
  script: /app/g2breve/g2BreveTest.py
  
  